### ISSUE TITLE
WPF MediaPlayerHost No MediaElement_MediaStateChanged Event

### ISSUE THREAD

**Issue by melinyi** [mysteryx93/MediaPlayerUI.NET#4]
we need 

` private void MediaElement_MediaStateChanged(object sender, MediaPlayerHost.Status e)`

**Comment by mysteryx93** [comment]
You got MediaLoaded, MediaError and MediaUnloaded events.

Additionally, you can listen to changes to the Status property. I just fixed properties in the Avalonia version because properties were not triggering PropertyChanged correctly; need to check WPF version for that too.

What more do you need?

**Comment by mysteryx93** [comment]
I checked the WPF code, it is raising change notification properly for Status correctly. It's only the Avalonia code that needed some tweaks.

Note that those events are in the inner player control, not on the MediaPlayer host.
